### ISSUE TITLE
Local Menu to not allow edit of selected item

### ISSUE THREAD

**Issue by lhengen** [DGH2112/Expert-Manager#1]
I just downloaded the ExpertManager for the first time.  It's a cool utility, but I noticed when I Rt. Clicked on the Known IDE Packages tab and selected Edit, that the contents of the previous tab selection were shown.  Not sure if this is related to your comment that the manager cannot access subkeys for IDE Packages, but it looks like a bug to me.

**Comment by DGH2112** [comment]
I can confirm that this is a bug that needs to be fixed.
The workaround is to use the Edit button on the toolbar at the top of the appropriate page.

**Comment by lhengen** [comment]
Thanks for the confirmation and your website with all the OpenTools API
help, it is a much better resource than EMBT's docwiki.

**Comment by DGH2112** [comment]
I've not forgotten, I've just had to work the weekend on the day job (not coding).

**Comment by DGH2112** [comment]
This has now been fixed ([Tags/1.3, Issue 2f919a4](https://github.com/DGH2112/Expert-Manager/commit/2f919a4c4c07b1755d8f1e8112fe3ecf54146956))
